// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://intjpmqgcordmfdrzmrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludGpwbXFnY29yZG1mZHJ6bXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODYwNDIsImV4cCI6MjA2NTk2MjA0Mn0.yUAON9wcySOYErxBDjlUoT7KUSYOk1qpi3y6hKmno6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);